apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BDTX78Kw/LmElcknaST/Jg==,iv:/Vq0rn9tO6WcxIuEk6U8vuhnrvfYLDoagIG+BuiosTU=,tag:h4JJOe8jhminzUJc4KVe3w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:PFg2+RDZJl7s6G0khRiAze5Cbhg=,iv:GclmrbQWf36Ke8q4q3jg5XvQM9athObGsnfwkmqd4RY=,tag:DVIwgpK3qtqTVgbj0ugFZw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/O10uYok/FOIj0I2SeCrL+WI2c0w8myjFJWLA9N0DV3AdUOm,iv:tid3M+QC9whAa8v/j/qCC0BX/inV9laXVEjCWZAwrhs=,tag:bAjkrpJhVp1K3vHNN9G2+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEODFFa3NvUkFyOFpoTWpQ
            dHREOTBGaGVsVUdFQWV2RTRUOWFubFQ0VVR3CngzTFM5aDVVQythYlBvM0V3VGZZ
            b1R6L2E4VmRramlSb1NaZmJsSlg3aW8KLS0tIGk4enFmQ1JOWnBOYmdYcEJVTTFM
            OGJ6L2hmKzhCejNpbDZiLzEzb0NTalEKH53/qLp+7MpSCTQrVqevSEvaIVEUiZ5c
            oP0IQYaRTuWbTM88ndTuiISbQrbpB3GHoGgK2a4zdeqIPWumwVGqgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T19:26:02Z"
    mac: ENC[AES256_GCM,data:xRCkPaan7mGfI7qRDOD4gqVbcGaBKwelewhTcjvpj+8ZyxVARbNQ6voTQ/vQUhfKZ03qa5XZszxtkKT8jyQ9CjO2S+KBx98ySFEQZBPmSApLSJiuQ6+koYFIKjARhy5cyNClpsKpB9cKwz8tdpixCyymfrALwg+tDdLn5JaMq/0=,iv:K06bCrUH8436wYguby4blLgOrYpVLVvEfoCH9vb1nks=,tag:cN76fNMXVHyQD2GV96dX1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
