apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:MdOC5Xo7F3d2lr1lYItBX9UkA2ZQeuon0S2c7BDQSE0=,iv:SGoXKswln0eXNA7KZoFL/G7BWSewEsVi//i2WWwpPJ0=,tag:bv06w53K5dZuY7Eecsi1zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWFMrVDFoWlNhZC9iRlA0
            Y2JIdWdnOHhNdnRBd1hSZmVFellyamxnTGp3CllwbUZDejI3S2N4UitFekIyOTU3
            Ylh2OHN3Nm15QnJJdGordkUvK2dLNmMKLS0tIERkaVBLMG5tRUd0dWgwck9QMEFn
            eS9tNlpnNldZeXlob1pLOGRDVnlIeDgKozK0hlxzoPuujUuY9sd6idZw5oRCffsa
            wey99aXOh14HVNSBe3jqKMXPWVWVhUrMj6VdFb+DBpxqIaHb66dApA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T19:26:02Z"
    mac: ENC[AES256_GCM,data:oV4M9UgPPuSs4c6mscrkqK1i/JXxg25WQVsDEN/jMLo2jEFzmnaXiy1U/mxZu5nMi1PWfim0lliZ4n1OYIyosrX7xAhl/xclOTqE6CHZccqhX46wUUztsXnlFcjyDU0NsJwxxqOP4f0Pq19KvFHaVwH5U+rjzqNdcBxRG9pHFgs=,iv:giouwmT3XDBv2WRTrV5LCJzDJT5NiZoiNRGJRBMowNg=,tag:3s1NjPgDFYXYLySYMvvlmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
