apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:56qL2oqW/i2qCdU5tRjZJN0jstD6ZiDmU+zb7gOOjSy4c0pm7ULygQ==,iv:pHPK+79dPAlHEAXCfoa5Lw11CSmfO0rMjb5xuIXcGQc=,tag:GOLnAhuMluOm9mh38tymIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWHQwZnZGdmdybE8zY0dY
            bGVSSEVnUzNDb0VBcjcyYU8wQk52UTQxVERjCllOQjZEQmlWS211V2lVZjhDaGVL
            U2U3OVdib0I1N3k4Q04wQzcrY2tSSFEKLS0tIFFCK1FUdlpSWFQxa0o1UkdVYWVQ
            MTUrTmd5c1h3R256Tisrb2Y3eUE0ZGsK+lq9y75rio82fLFG7rahOmTvWRS2fePD
            88KnmsMbTMXhoAW3R8t9O/qgmL+JYdqAifg5Nlh5P55qf82Z7pep7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T19:26:02Z"
    mac: ENC[AES256_GCM,data:xYFGBqDi1JeP8RRy2NXxn7IknXfXDvaxoJRdIJXMun4y2xTRr08S3ed0NStfMAoyLfW3CWx8YyhOVNgAbIBkx2TYxrG7FsbNKRbZ83TV+bnyzHty2kgYBsOF0VdrpIngxJv+p/XnWU8Ki6Ui9JG0iqZwlftx8EkWlZdAyI2YK04=,iv:MLD59PzjGZ6tEwj0XEwkK7QeNzUnJXhX1OhGWStEAQE=,tag:0ekXY6Izphi1j9Q1A+pWmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
